### ISSUE TITLE
Cannot install on Ubuntu 14.04.5 LTS and Python 3.5.2

### ISSUE THREAD

**Issue by igorposmashny** [erdem/django-map-widgets#11]
Hi!
I trying to install package with virtualenv on ubuntu 14.04.5 LTS. I have python 3.5.2. 
After 
`pip install django-map-widgets`
i have this traceback:
```
Collecting django-map-widgets
  Downloading django-map-widgets-0.1.7.tar.gz (143kB)
    100% |################################| 143kB 31.9MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-4zpnyqzn/django-map-widgets/setup.py", line 10, in <module>
        long_description = open(readme_rst).read()
      File "/home/ubuntu/www/punkapp/venv/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 424: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-4zpnyqzn/django-map-widgets/
```

**Comment by erdem** [comment]
This issue seems a system localisation issue. I don't know which locale setup on your system but you can set locale settings with the following command on the current terminal session.

`export LC_ALL="en_US.UTF-8"`

`pip install django-map-widgets` should work after this command.

**Comment by igorposmashny** [comment]
Thank you @erdem !
it helped 👍
